apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: loswaldo
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.50
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "healthcheck.sh"
          initialDelaySeconds: 30
          periodSeconds: 5
