apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: loswaldo
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.50
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "healthcheck.sh"
          initialDelaySeconds: 30
          periodSeconds: 5
