apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: loswaldo
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.50
  selector:
    app: ftps
  ports:
  - name: first
    protocol: TCP
    port: 20
    targetPort: 20
  - name: second
    protocol: TCP
    port: 21
    targetPort: 21
  - name: third
    protocol: TCP
    port: 30000
    targetPort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 21
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "healthcheck.sh"
          initialDelaySeconds: 30
          periodSeconds: 5
